name: nccasino
version: '1.0-SNAPSHOT'
main: org.nc.nccasino.Nccasino
api-version: '1.21'
commands:
  ncc:
    description: Main command for the Nccasino plugin
    aliases: [nccasino]
    usage: /ncc <subcommand>
    permission: nccasino.use
permissions:
  nccasino.use:
    description: Allows use of the /ncc and /nccasino commands
    default: op